{
    "swagger": "2.0",
    "info": {
        "title": "Travel API",
        "description": "Interfejs do sprzedaży produktów turystycznych oferowanych przez Towarzystwo Ubezpieczeń Europa S. A.\n\nWszelkie komunikaty opisywane w tym dokumencie są przesyłane przy użyciu funkcji INVOKE opisanej w dokumencie Specyfikacja_ESB.pdf.",
        "version": "1.4.2-draft",
        "termsOfService": "",
        "contact": {
            "name": "API Support",
            "url": "http://www.tueuropa.pl",
            "email": "apisupport@tueuropa.pl"
        }
    },
    "host": "api.tueuropa.pl",
    "schemes": [
        "https"
    ],
    "produces": [
        "per \"application/json\""
    ],
    "paths": {
        "/travel/v1/import_policies": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Import gotowych polis do systemu",
                "description": "Funkcja zapisuje polisy w systemie TU.",
                "parameters": [
                    {
                        "name": "data",
                        "in": "body",
                        "description": "Parametry zapisywanej polisy",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/IMPORT_REQUEST"
                            }
                        }
                    },
                    {
                        "name": "customer_id",
                        "in": "query",
                        "description": "Identyfikator klienta otrzymany od TU Europa (parametr uzupełniany automatycznie przy połączeniu przez ESB).",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "request_id",
                        "in": "query",
                        "description": "Identyfikator żądania (parametr uzupełniany automatycznie przy połączeniu przez ESB).",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Potwierdzenie importu",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/IMPORT_STATUS"
                            }
                        }
                    },
                    "303": {
                        "description": "Zaimportowane, wystąpiły błędy",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/IMPORT_STATUS"
                            }
                        }
                    },
                    "400": {
                        "description": "Błędne żądanie",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/VALIDATION_ERROR"
                            }
                        }
                    },
                    "401": {
                        "description": "Błąd identyfikacji klienta",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ERROR"
                            }
                        }
                    },
                    "403": {
                        "description": "Błąd autoryzacji klienta",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ERROR"
                            }
                        }
                    },
                    "404": {
                        "description": "Nie znaleziono żądanego zasobu",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ERROR"
                            }
                        }
                    },
                    "406": {
                        "description": "Błąd identyfikacji żądania w ciągu zapytań",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ERROR"
                            }
                        }
                    },
                    "422": {
                        "description": "Błąd walidacji danych",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/VALIDATION_ERROR"
                            }
                        }
                    },
                    "500": {
                        "description": "Błąd wewnętrzny serwera",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ERROR"
                            }
                        }
                    },
                    "default": {
                        "description": "Niespodziewany błąd",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ERROR"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ADDRESS": {
            "type": "object",
            "description": "Dane adresowe",
            "properties": {
                "country": {
                    "type": "string",
                    "pattern": "^[A-Z]{2}$",
                    "description": "Kraj (kod kraju zgodny z ISO 3166-1 alpha-2)"
                },
                "post_code": {
                    "type": "string",
                    "description": "Kod pocztowy",
                    "minLength": 1
                },
                "city": {
                    "type": "string",
                    "description": "Miejscowość",
                    "minLength": 1
                },
                "street": {
                    "type": "string",
                    "description": "Ulica",
                    "minLength": 1
                },
                "house_no": {
                    "type": "string",
                    "description": "Numer domu",
                    "minLength": 1
                },
                "flat_no": {
                    "type": "string",
                    "description": "Numer mieszkania",
                    "minLength": 1
                }
            },
            "required": [
                "country",
                "post_code",
                "city",
                "street",
                "house_no"
            ],
            "example": {
                "country": "PL",
                "post_code": "53-413",
                "city": "Wrocław",
                "street": "Gwiaździsta",
                "house_no": "62",
                "flat_no": "6"
            }
        },
        "AGREEMENT": {
            "type": "object",
            "description": "Zgoda (np. marketingowa)",
            "properties": {
                "description": {
                    "type": "string",
                    "description": "Treść zgody",
                    "minLength": 1
                },
                "value": {
                    "type": "boolean",
                    "description": "Wartość zgody"
                },
                "code": {
                    "type": "string",
                    "description": "Kod zgody",
                    "minLength": 1
                }
            },
            "required": [
                "description",
                "value",
                "code"
            ],
            "example": {
                "description": "Oświadczam, iż przed zawarciem umowy ubezpieczeniowej zapoznałem się z Ogólnymi Warunkami Ubezpieczenia, na podstawie których zostałem objęty ochroną ubezpieczeniową przez TU Europa S.A.",
                "value": true,
                "code": "zgodam"
            }
        },
        "AMOUNT": {
            "type": "object",
            "description": "Składka",
            "properties": {
                "value_base": {
                    "type": "number",
                    "format": "float",
                    "description": "Kwota składki w walucie podstawowej"
                },
                "value_base_currency": {
                    "type": "string",
                    "pattern": "^[A-Z]{3}$",
                    "description": "Waluta podstawowa (kod waluty zgodny z ISO 4217)"
                },
                "value": {
                    "type": "number",
                    "format": "float",
                    "description": "Kwota składki"
                },
                "value_currency": {
                    "type": "string",
                    "pattern": "^[A-Z]{3}$",
                    "description": "Waluta (kod waluty zgodny z ISO 4217)"
                },
                "currency_rate": {
                    "type": "number",
                    "format": "float",
                    "description": "Kurs waluty"
                },
                "date_rate": {
                    "type": "string",
                    "format": "date-time",
                    "description": "Data kursu"
                }
            },
            "required": [
                "value_base",
                "value_base_currency",
                "value",
                "value_currency",
                "currency_rate",
                "date_rate"
            ],
            "example": {
                "value_base": 100.23,
                "value_base_currency": "PLN",
                "value": 29,
                "value_currency": "EUR",
                "currency_rate": 3.4567,
                "date_rate": "2015-12-02T12:12:12+01:00"
            }
        },
        "ERROR": {
            "type": "object",
            "description": "Błąd",
            "properties": {
                "description": {
                    "type": "string",
                    "description": "Opis błędu",
                    "minLength": 1
                }
            },
            "example": {
                "property": "end_date",
                "errors": [
                    "Data zakończenie nie może być wcześniejsza niż data rozpoczęcia",
                    "Data zakończenia nie może być pusta"
                ]
            }
        },
        "IMPORT_REQUEST": {
            "type": "object",
            "description": "Zestaw danych do zapisania gotowej polisy",
            "properties": {
                "product_ref": {
                    "type": "string",
                    "description": "Identyfikator produktu",
                    "minLength": 1
                },
                "data": {
                    "$ref": "#/definitions/POLICY_DATA",
                    "description": "Dane polisy"
                },
                "payment_date": {
                    "type": "string",
                    "format": "date-time",
                    "description": "Data zapłaty"
                },
                "policy_date": {
                    "type": "string",
                    "format": "date-time",
                    "description": "Data zawarcia polisy"
                },
                "policy_number": {
                    "type": "string",
                    "description": "Numer polisy",
                    "minLength": 1
                },
                "policy_holder": {
                    "$ref": "#/definitions/POLICY_HOLDER",
                    "description": "Dane ubezpieczającego"
                },
                "insured": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/INSURED"
                    },
                    "minItems": 1,
                    "description": "Dane ubezpieczonych"
                },
                "amount": {
                    "$ref": "#/definitions/AMOUNT",
                    "description": "Obiekt z informacją o składce pobranej"
                },
                "tariff_amount": {
                    "$ref": "#/definitions/AMOUNT",
                    "description": "Obiekt z informacją o składce wynikającej z taryfy"
                },
                "netto_amount": {
                    "$ref": "#/definitions/AMOUNT",
                    "description": "Obiekt z informacją o składce netto"
                },
                "promo_code": {
                    "type": "string",
                    "description": "Kod promocyjny",
                    "minLength": 1
                },
                "solicitors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SOLICITOR"
                    },
                    "minItems": 1,
                    "description": "Informacje o OWCA biorących udział w sprzedaży polisy; Wartości tego pola są weryfikowane a dokładnie uprawnienia agenta/owca do sprzedaży danego typu polisy"
                }
            },
            "required": [
                "product_ref",
                "data",
                "policy_date",
                "policy_number",
                "policy_holder",
                "insured",
                "amount",
                "tariff_amount",
                "netto_amount",
                "solicitors"
            ],
            "example": {
                "product_ref": "55ac435aabb4760c03fc3568",
                "data": {},
                "payment_date": "2015-12-02T12:12:10+01:00",
                "policy_date": "2015-12-02T12:12:12+01:00",
                "policy_holder": {},
                "insured": [],
                "amount": {},
                "tariff_amount": {},
                "netto_amount": {},
                "promo_code": {},
                "solicitors": []
            }
        },
        "IMPORT_STATUS": {
            "type": "object",
            "description": "Opis statusu importu polisy",
            "properties": {
                "status": {
                    "type": "string",
                    "enum": [
                        "OK",
                        "WARN",
                        "ERR"
                    ],
                    "description": "Status importu polisy"
                },
                "policy_ref": {
                    "type": "string",
                    "description": "Identyfikator polisy",
                    "minLength": 1
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "code": {
                                "type": "string",
                                "description": "Kod błędu",
                                "minLength": 1
                            },
                            "text": {
                                "type": "string",
                                "description": "Opis błędu",
                                "minLength": 1
                            }
                        }
                    }
                }
            },
            "required": [
                "status"
            ],
            "example": {
                "status": "OK",
                "policy_ref": "54fc43dfabb4760c04dc3569",
                "messages": []
            }
        },
        "INSURED": {
            "type": "object",
            "description": "Ubezpieczony",
            "properties": {
                "data": {
                    "$ref": "#/definitions/PERSON_DATA",
                    "description": "Dane osobowe"
                },
                "address": {
                    "$ref": "#/definitions/ADDRESS",
                    "description": "Dane adresowe"
                },
                "option_values": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OPTION_VALUE"
                    },
                    "description": "Tablica wartości dodatkowych atrybutów"
                }
            },
            "required": [
                "data"
            ],
            "example": {
                "data": {},
                "address": {},
                "option_values": []
            }
        },
        "OPTION_DEFINITION": {
            "type": "object",
            "description": "Definicja atrybutu",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Nazwa atrybutu",
                    "minLength": 1
                },
                "description": {
                    "type": "string",
                    "description": "Opis atrybutu",
                    "minLength": 1
                },
                "code": {
                    "type": "string",
                    "description": "Kod atrybutu",
                    "minLength": 1
                },
                "value_type": {
                    "type": "string",
                    "default": "string",
                    "enum": [
                        "string",
                        "number",
                        "date",
                        "boolean"
                    ],
                    "description": "Oczekiwany typ danych wartości atrybutu"
                },
                "changeable": {
                    "type": "boolean",
                    "description": "Czy jest możliwa zmiana wartości tego atrybutu"
                },
                "sub_options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OPTION_DEFINITION"
                    },
                    "description": "Tablica definicji atrybutów"
                }
            },
            "required": [
                "name",
                "description",
                "code",
                "value_type",
                "changeable"
            ],
            "example": {
                "name": "Komfortowa Kieszeń",
                "description": "Komfortowa Kieszeń - ubezpieczenie telefonu komórkowego, dokumentów, portfela od kradzieży z włamaniem i rabunku podczas podróży.",
                "code": "TWKK",
                "value_type": "number",
                "changeable": true,
                "sub_options": []
            }
        },
        "OPTION_VALUE": {
            "type": "object",
            "description": "Wartość atrybutu",
            "properties": {
                "code": {
                    "type": "string",
                    "description": "Kod atrybutu",
                    "minLength": 1
                },
                "value": {
                    "type": "string",
                    "description": "Wartość atrybutu"
                },
                "sub_options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OPTION_VALUE"
                    },
                    "description": "Tablica wartości dodatkowych atrybutów"
                }
            },
            "required": [
                "code",
                "value"
            ],
            "example": {
                "code": "TWKK",
                "value": "5000",
                "sub_options": []
            }
        },
        "SOLICITOR": {
            "type": "object",
            "description": "OWCA",
            "properties": {
                "solicitor_id": {
                    "type": "string",
                    "description": "Identyfikator OWCY w rejestrze KNF (tzw numer RA)"
                },
                "agent_id": {
                    "type": "string",
                    "description": "Identyfikator Agenta w systemi KNF (tzw numer RA agenta)"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "ADM",
                            "DDZ",
                            "ZAW"
                        ],
                        "description": "Rodzaj uprawnienia, która wykorzustuje agent podczas kontaktu z klientem (ADM - administracja, DDZ -  doprowadzenie, ZAW - zawarcie)"
                    },
                    "description": "Wykorzystane uprawnienia"
                }
            }
        },
        "PERSON_DATA": {
            "type": "object",
            "description": "Dane osoby",
            "properties": {
                "first_name": {
                    "type": "string",
                    "description": "Imię",
                    "minLength": 1
                },
                "last_name": {
                    "type": "string",
                    "description": "Nazwisko",
                    "minLength": 1
                },
                "birth_date": {
                    "type": "string",
                    "format": "date",
                    "description": "Data urodzenia"
                },
                "pesel": {
                    "type": "string",
                    "description": "Numer PESEL",
                    "pattern": "^[0-9]{11}$"
                },
                "nationality": {
                    "type": "string",
                    "pattern": "^[A-Z]{2}$",
                    "description": "Obywatelstwo (kod kraju zgodny z ISO 3166-1 alpha-2)"
                },
                "document_no": {
                    "type": "string",
                    "description": "Numer dokumentu tożsamości",
                    "minLength": 1
                },
                "business_name": {
                    "type": "string",
                    "description": "Nazwa działalności",
                    "minLength": 1
                },
                "short_business_name": {
                    "type": "string",
                    "description": "Skrócona nazwa działalności",
                    "minLength": 1
                },
                "nip": {
                    "type": "string",
                    "description": "NIP",
                    "pattern": "^[0-9]{10}$"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "private",
                        "sole_trader",
                        "company",
                        "foreigner"
                    ],
                    "description": "Typ osoby"
                }
            },
            "required": [
                "type"
            ],
            "example": {
                "first_name": "Jan",
                "last_name": "Kowalski",
                "birth_date": "1950-11-25",
                "pesel": "50112502677",
                "nationality": "PL",
                "document_no": "AJG122578",
                "type": "private"
            }
        },
        "POLICY_DATA": {
            "type": "object",
            "description": "Dane polisy",
            "properties": {
                "promo_code": {
                    "type": "string",
                    "description": "Kod promocyjny",
                    "minLength": 1
                },
                "start_date": {
                    "type": "string",
                    "format": "date-time",
                    "description": "Data rozpoczęcia ochrony"
                },
                "end_date": {
                    "type": "string",
                    "format": "date-time",
                    "description": "Data zakończenia ochrony"
                },
                "abroad": {
                    "type": "boolean",
                    "description": "Czy ubezpieczony przebywa za granicą Polski w momencie przystąpienia do ubezpieczenia (informacja ważna ze względu na ewentualną karencję w ochronie ubezpieczeniowej)"
                },
                "destination": {
                    "type": "string",
                    "pattern": "^[A-Z]{2}$",
                    "description": "Cel podróży (kod kraju określony w ISO 3166-1 alpha-2 lub EU - Unia Europejska lub WR - świat)"
                },
                "option_values": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OPTION_VALUE"
                    },
                    "description": "Tablica wartości dodatkowych atrybutów"
                }
            },
            "required": [
                "start_date",
                "end_date"
            ],
            "example": {
                "promo_code": "KOD2002",
                "start_date": "2001-02-02",
                "end_date": "2001-02-10",
                "abroad": true,
                "destination": "EU",
                "option_values": []
            }
        },
        "POLICY_HOLDER": {
            "type": "object",
            "description": "Ubezpieczający",
            "properties": {
                "data": {
                    "$ref": "#/definitions/PERSON_DATA",
                    "description": "Dane osobowe"
                },
                "address": {
                    "$ref": "#/definitions/ADDRESS",
                    "description": "Dane adresowe"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "description": "Adres e-mail"
                },
                "telephone": {
                    "type": "string",
                    "description": "Numer telefonu",
                    "pattern": "^\\+((48[0-9]{9})|((?!48)[0-9]{6,15}))$"
                },
                "agreements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/AGREEMENT"
                    },
                    "description": "Informacja o wyrażonych/odrzuconych zgodach"
                }
            },
            "required": [
                "data",
                "agreements"
            ],
            "example": {
                "data": {},
                "address": {},
                "email": "j.kowalski@poczta.pl",
                "telephone": "+48123456789",
                "agreements": []
            }
        },
        "VALIDATION_ERROR": {
            "type": "object",
            "description": "Błąd walidacji",
            "properties": {
                "property": {
                    "type": "string",
                    "description": "Nazwa atrybutu, którego dotyczą błędy"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "description": "Opis błędu",
                        "minLength": 1
                    },
                    "minItems": 1,
                    "description": "Tablica opisów błędów"
                }
            },
            "required": [
                "property",
                "errors"
            ],
            "example": {
                "property": "end_date",
                "errors": [
                    "Data zakończenie nie może być wcześniejsza niż data rozpoczęcia",
                    "Data zakończenia nie może być pusta"
                ]
            }
        }
    }
}